name: Pull request on develop
on:
  pull_request:
    branches:
      - develop

jobs:
  flutter_test:
    name: Run flutter analyze and test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: "12.x"
      - uses: subosito/flutter-action@v1
        with:
          channel: "stable"
      - run: flutter pub get
      - run: flutter analyze
      - run: flutter test
      - uses: erickzanardo/flutter-gh-pages@v3
        with:
          workingDir: docs